### PR TITLE
Button component

### PR DESCRIPTION
**Pull request by Sh11ntar0**
Change the button styles.
Please check it.

### CODE REVIEW

**Review by BlackStone8960 — CHANGES_REQUESTED** [review]
Thank you, it looks good!
But it looks like there are still some differences between mock up and this styling.

1. The margin between two buttons to register on top page looks different from mock up. 1st picture is from mockup, and 2nd one is from current layout. The same problem is happened at header as well.

Screen Shot 2021-12-19 at 7 11 44 AM

Screen Shot 2021-12-19 at 7 11 20 AM

2. The hovering style of very buttom buttons at top page are different from other buttons, but is this okay for a designer?

Button-hovering

Can you check it when you have time?
Thank you!

**Comment by Sh11ntar0** [comment]
@BlackStone8960 
I've fixed those issues.
Could you check them?

**Review by BlackStone8960 — COMMENTED** [review]
Sorry, could you fix the style of buttons at header as well? You can add margin-right to left button that says "無料会員登録".

**Comment by Sh11ntar0** [comment]
@BlackStone8960 
I fixed it!

**Review by BlackStone8960 — APPROVED** [review]
Looks good! Thank you for fixing it

**Pull request merged**
